# Site settings
title: Overyonder IT Solutions
email: kai@kai.systems
description: "This is a small IT business run by Kieran Hannigan. Drop me an email with any queries!"
baseurl: ""
url: "http://oys.kai.systems"

# Build settings
markdown: kramdown
permalink: pretty
